import 'package:flutter/material.dart';
//import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart'; // Generated by flutterfire configure
import 'signup_page.dart';
import 'splash_screen.dart'; // Import the splash screen
// import 'slidescreenbg.dart';
// import 'welcome_screen.dart'; // Import the welcome screen
import 'login_page.dart'; // Import the login page
import 'home_page.dart'; // Import the home page
import 'forgot_password.dart'; // Import the forgot password page



void main() {
  WidgetsFlutterBinding.ensureInitialized(); // Ensures async initialization is handled
  runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'POS System',
      home: const LoginScreen(),
      theme: ThemeData(
        primarySwatch: Colors.purple,
      ),
      initialRoute: '/splash',
      routes: {
        '/splash': (context) => const SplashScreen(),
        // '/intro': (context) => const SlideScreen(),
        // '/welcome': (context) => const WelcomeScreen(), // Add welcome screen route
        '/login': (context) => const LoginScreen(), // Add login screen route
        '/home': (context) => const HomePage(),
        '/forgot_password': (context) => const ForgotPassword(),
        '/signup': (context) => const SignupScreen(), // Add this line in routes
      },
    );
  }
}
